language: java

script: make build

before_deploy: make docs

deploy:
  # deploy to GitHub Pages
  provider: pages
  local_dir: docs
  name: bot50
  email: bot@cs50.harvard.edu
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
